- hosts: all
  become: yes
  tasks:
  - name: make dirs 
    file: 
      path: "{{item}}"
      state: directory
    with_items:
      - /opt/app
      - /opt/app/templates


  - name: copy app file
    copy:
      src: /var/lib/jenkins/workspace/flask-app_master/app.py
      dest: /opt/app/app.py


  - name: copy app file
    copy:
      src: /var/lib/jenkins/workspace/flask-app_master/templates/index.html
      dest: /opt/app/templates/index.html

  - debug:
      msg: "{{item}}"
    with_items:
      - "{{ lookup('env') }}

