- hosts: all
  become: yes
  vars:
    workspace: "{{ lookup('env','WORKSPACE') }}"
  tasks:
  - name: make dirs 
    file: 
      path: "{{item}}"
      state: directory
    with_items:
      - /opt/app
      - /opt/app/templates


  - name: copy app file
    copy:
      src: "{{workspace}}/app.py"
      dest: /opt/app/app.py


  - name: copy app file
    copy:
      src: "{{workspace}}/templates/index.html"
      dest: /opt/app/templates/index.html

#  - debug:
#      msg: "{{item}}"
#    with_items:
#      - "{{ lookup('env','WORKSPACE') }}"

